spring.datasource.url=jdbc:postgresql://localhost:5432/postalcodesearch_db_dev
spring.datasource.username=postgres
spring.datasource.password=csystem-1993
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-dev.sql,classpath:schema.sql
spring.sql.init.data-locations=classpath:data-dev.sql
