spring.application.name=RoleBaseUsersInMemoryAuth

spring.datasource.url=jdbc:postgresql://localhost:5432/postalcodesearch_db
spring.datasource.username=postgres
spring.datasource.password=csystem-1993

server.port=6767

geonames.postalcodesearch.url=http://api.geonames.org/postalCodeSearchJSON?postalcode=%s&maxRows=%d&username=csystem

