spring.application.name=RoleBaseUsersInMemoryAuth

spring.datasource.url=jdbc:postgresql://localhost:5432/demorestsec_db
spring.datasource.username=postgres
spring.datasource.password=csystem-1993

server.port=6767

